#!/usr/bin/env python3
from __future__ import annotations

import argparse
import os
import re
import signal
import subprocess
import sys
import threading
import time
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / "output" / "site-health.md"
KEY_VALUE_RE = re.compile(r"^([A-Za-z0-9_:-]+)=(.*)$")
PROGRESS_PREFIXES = ("[visual]", "[public-quiz-flow]", "[perf]", "[tap]", "[public-visual]")


CHECKS = [
    ("predeploy", [sys.executable, "tools/predeploy_check.py"], 180, False),
    ("cloudflare_dry_run", [sys.executable, "tools/deploy_cloudflare_pages.py", "--dry-run"], 120, False),
    ("public_accessibility_smoke", [sys.executable, "tools/public_accessibility_smoke.py"], 240, True),
    ("public_asset_integrity_smoke", [sys.executable, "tools/public_asset_integrity_smoke.py"], 240, True),
    ("public_deploy_smoke", [sys.executable, "tools/public_deploy_smoke.py"], 240, True),
    ("public_launch_link_smoke", [sys.executable, "tools/public_launch_link_smoke.py"], 240, True),
    ("public_contact_smoke", [sys.executable, "tools/public_contact_smoke.py"], 120, True),
    ("public_discovery_smoke", [sys.executable, "tools/public_discovery_smoke.py"], 180, True),
    ("public_support_sync_smoke", [sys.executable, "tools/public_support_sync_smoke.py"], 180, True),
    ("public_promotion_kit_smoke", [sys.executable, "tools/public_promotion_kit_smoke.py"], 120, True),
    ("public_external_link_smoke", [sys.executable, "tools/public_external_link_smoke.py"], 120, True),
    ("public_garden_map_smoke", [sys.executable, "tools/public_garden_map_smoke.py"], 180, True),
    ("public_guide_smoke", [sys.executable, "tools/public_guide_smoke.py"], 300, True),
    ("public_guardian_smoke", [sys.executable, "tools/public_guardian_smoke.py"], 240, True),
    ("public_headers_smoke", [sys.executable, "tools/public_headers_smoke.py"], 120, True),
    ("public_home_smoke", [sys.executable, "tools/public_home_smoke.py"], 180, True),
    ("public_indexability_smoke", [sys.executable, "tools/public_indexability_smoke.py"], 240, True),
    ("public_internal_link_smoke", [sys.executable, "tools/public_internal_link_smoke.py"], 300, True),
    ("public_keepsake_smoke", [sys.executable, "tools/public_keepsake_smoke.py"], 180, True),
    ("public_locale_route_smoke", [sys.executable, "tools/public_locale_route_smoke.py"], 240, True),
    ("public_locale_ui_smoke", [sys.executable, "tools/public_locale_ui_smoke.py"], 240, True),
    ("public_luna_smoke", [sys.executable, "tools/public_luna_smoke.py"], 180, True),
    ("public_metadata_smoke", [sys.executable, "tools/public_metadata_smoke.py"], 240, True),
    ("public_quiz_conversion_smoke", [sys.executable, "tools/public_quiz_conversion_smoke.py"], 240, True),
    ("public_quiz_data_smoke", [sys.executable, "tools/public_quiz_data_smoke.py"], 120, True),
    ("public_quiz_flow_smoke", ["node", "tools/public_quiz_flow_smoke.mjs"], 180, True),
    ("public_revenue_path_smoke", [sys.executable, "tools/public_revenue_path_smoke.py"], 180, True),
    ("public_repair_plan_smoke", [sys.executable, "tools/public_repair_plan_smoke.py"], 180, True),
    ("public_schema_smoke", [sys.executable, "tools/public_schema_smoke.py"], 240, True),
    ("public_schema_url_smoke", [sys.executable, "tools/public_schema_url_smoke.py"], 240, True),
    ("public_sitemap_smoke", [sys.executable, "tools/public_sitemap_smoke.py"], 240, True),
    ("public_supply_smoke", [sys.executable, "tools/public_supply_smoke.py"], 180, True),
    ("public_not_found_smoke", ["node", "tools/public_not_found_smoke.mjs"], 120, True),
    ("public_visual_smoke", ["node", "tools/public_visual_smoke.mjs"], 1500, True),
    ("csp_runtime_smoke", ["node", "tools/csp_runtime_smoke.mjs"], 120, True),
    ("public_trust_smoke", [sys.executable, "tools/public_trust_smoke.py"], 180, True),
    ("public_versioned_asset_smoke", [sys.executable, "tools/public_versioned_asset_smoke.py"], 240, True),
    ("promotion_spreadsheet_workbook", ["node", "tools/build_promotion_spreadsheet.mjs", "--check"], 120, False),
    ("promotion_metric_source_matrix", [sys.executable, "tools/promotion_metric_source_matrix.py", "--check"], 120, False),
    ("promotion_data_collection_sheet", [sys.executable, "tools/promotion_data_collection_sheet.py", "--check"], 120, False),
    ("promotion_kpi_schema_audit", [sys.executable, "tools/promotion_kpi_schema_audit.py"], 120, False),
    ("promotion_attribution_reconciliation", [sys.executable, "tools/promotion_attribution_reconciliation.py", "--check"], 120, False),
    ("promotion_platform_kpi_tracker", [sys.executable, "tools/promotion_platform_kpi_tracker.py", "--check"], 120, False),
    ("promotion_launch_readiness_gate", [sys.executable, "tools/promotion_launch_readiness_gate.py", "--check"], 120, False),
    ("promotion_evidence_ledger", [sys.executable, "tools/promotion_evidence_ledger.py", "--check"], 120, False),
    ("promotion_profile_setup_runbook", [sys.executable, "tools/promotion_profile_setup_runbook.py", "--check"], 120, False),
    ("promotion_profile_completion_gate", [sys.executable, "tools/promotion_profile_completion_gate.py", "--check"], 120, False),
    ("promotion_week_publication_runbook", [sys.executable, "tools/promotion_week_publication_runbook.py", "--week", "1", "--check"], 120, False),
    ("promotion_platform_account_identity_checklist", [sys.executable, "tools/promotion_platform_account_identity_checklist.py", "--check"], 120, False),
    ("promotion_profile_setup_action_sheet", [sys.executable, "tools/promotion_profile_setup_action_sheet.py", "--check"], 120, False),
    ("promotion_profile_link_readiness_packet", [sys.executable, "tools/promotion_profile_link_readiness_packet.py", "--check"], 120, False),
    ("promotion_profile_proof_readiness_pack", [sys.executable, "tools/promotion_profile_proof_readiness_pack.py", "--check"], 120, False),
    ("promotion_first_batch_publish_action_sheet", [sys.executable, "tools/promotion_first_batch_publish_action_sheet.py", "--check"], 120, False),
    ("promotion_first_batch_publish_readiness_pack", [sys.executable, "tools/promotion_first_batch_publish_readiness_pack.py", "--check"], 120, False),
    ("promotion_first_batch_kpi_action_sheet", [sys.executable, "tools/promotion_first_batch_kpi_action_sheet.py", "--check"], 120, False),
    ("promotion_operation_proof_templates", [sys.executable, "tools/promotion_operation_proof_templates.py", "--check"], 120, False),
    ("promotion_profile_evidence_checklist", [sys.executable, "tools/promotion_profile_evidence_checklist.py", "--check"], 120, False),
    ("promotion_first_batch_publish_checklist", [sys.executable, "tools/promotion_first_batch_publish_checklist.py", "--check"], 120, False),
    ("promotion_first_batch_kpi_checklist", [sys.executable, "tools/promotion_first_batch_kpi_checklist.py", "--check"], 120, False),
    ("promotion_profile_post_alignment_checklist", [sys.executable, "tools/promotion_profile_post_alignment_checklist.py", "--check"], 120, False),
    ("promotion_public_post_url_checklist", [sys.executable, "tools/promotion_public_post_url_checklist.py", "--check"], 120, False),
    ("promotion_zero_kpi_evidence_checklist", [sys.executable, "tools/promotion_zero_kpi_evidence_checklist.py", "--check"], 120, False),
    ("promotion_post_ops_readiness_pack", [sys.executable, "tools/promotion_post_ops_readiness_pack.py", "--check"], 120, False),
    ("promotion_first_batch_evidence_matrix", [sys.executable, "tools/promotion_first_batch_evidence_matrix.py", "--check"], 120, False),
    ("promotion_first_batch_completion_gate", [sys.executable, "tools/promotion_first_batch_completion_gate.py", "--check"], 120, False),
    ("promotion_decision_readiness_checklist", [sys.executable, "tools/promotion_decision_readiness_checklist.py", "--check"], 120, False),
    ("promotion_decision_input_matrix", [sys.executable, "tools/promotion_decision_input_matrix.py", "--check"], 120, False),
    ("promotion_weekly_decision_evidence_checklist", [sys.executable, "tools/promotion_weekly_decision_evidence_checklist.py", "--check"], 120, False),
    ("promotion_weekly_review_action_sheet", [sys.executable, "tools/promotion_weekly_review_action_sheet.py", "--check"], 120, False),
    ("promotion_blocker_resolution_checklist", [sys.executable, "tools/promotion_blocker_resolution_checklist.py", "--check"], 120, False),
    ("promotion_lead_evidence_checklist", [sys.executable, "tools/promotion_lead_evidence_checklist.py", "--check"], 120, False),
    ("promotion_lead_demand_gate", [sys.executable, "tools/promotion_lead_demand_gate.py", "--check"], 120, False),
    ("promotion_lead_ops_action_sheet", [sys.executable, "tools/promotion_lead_ops_action_sheet.py", "--check"], 120, False),
    ("promotion_lead_request_proof_packet", [sys.executable, "tools/promotion_lead_request_proof_packet.py", "--check"], 120, False),
    ("promotion_asset_fulfillment_gate", [sys.executable, "tools/promotion_asset_fulfillment_gate.py", "--check"], 120, False),
    ("promotion_master_gate", [sys.executable, "tools/promotion_master_gate.py", "--check"], 120, False),
    ("promotion_stage_transition_matrix", [sys.executable, "tools/promotion_stage_transition_matrix.py", "--check"], 120, False),
    ("promotion_profile_publish_handoff", [sys.executable, "tools/promotion_profile_publish_handoff.py", "--check"], 120, False),
    ("promotion_publish_kpi_handoff", [sys.executable, "tools/promotion_publish_kpi_handoff.py", "--check"], 120, False),
    ("promotion_weekly_lead_offer_handoff", [sys.executable, "tools/promotion_weekly_lead_offer_handoff.py", "--check"], 120, False),
    ("promotion_launch_ops_dashboard", [sys.executable, "tools/promotion_launch_ops_dashboard.py", "--check"], 120, False),
    ("promotion_launch_day_run_sheet", [sys.executable, "tools/promotion_launch_day_run_sheet.py", "--check"], 120, False),
    ("promotion_launch_exception_runbook", [sys.executable, "tools/promotion_launch_exception_runbook.py", "--check"], 120, False),
    ("runtime_performance_smoke", ["node", "tools/runtime_performance_smoke.mjs"], 120, True),
    ("keyboard_navigation_smoke", ["node", "tools/keyboard_navigation_smoke.mjs"], 120, True),
    ("tap_target_smoke", ["node", "tools/tap_target_smoke.mjs"], 120, True),
    ("contrast_smoke", ["node", "tools/contrast_smoke.mjs"], 120, True),
    ("user_preferences_smoke", ["node", "tools/user_preferences_smoke.mjs"], 120, True),
    ("storage_privacy_smoke", ["node", "tools/storage_privacy_smoke.mjs"], 120, True),
]
RETRY_ON_FAILURE = {
    "csp_runtime_smoke",
    "keyboard_navigation_smoke",
    "public_launch_link_smoke",
    "public_locale_ui_smoke",
    "public_quiz_flow_smoke",
    "public_schema_url_smoke",
    "runtime_performance_smoke",
    "tap_target_smoke",
}


def should_stream_progress(line: str) -> bool:
    stripped = line.strip()
    return any(stripped.startswith(prefix) for prefix in PROGRESS_PREFIXES)


def terminate_process_tree(process: subprocess.Popen[str]) -> None:
    try:
        os.killpg(process.pid, signal.SIGTERM)
    except ProcessLookupError:
        return
    except OSError:
        process.terminate()
    try:
        process.wait(timeout=5)
        return
    except subprocess.TimeoutExpired:
        pass
    try:
        os.killpg(process.pid, signal.SIGKILL)
    except ProcessLookupError:
        return
    except OSError:
        process.kill()


def run(command: list[str], timeout: int = 180) -> tuple[int, str]:
    started = time.monotonic()
    process = subprocess.Popen(
        command,
        cwd=ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.STDOUT,
        bufsize=1,
        start_new_session=True,
    )
    output_lines: list[str] = []

    def collect_output() -> None:
        assert process.stdout is not None
        for line in process.stdout:
            output_lines.append(line)
            if should_stream_progress(line):
                print(line.rstrip(), flush=True)

    reader = threading.Thread(target=collect_output, daemon=True)
    reader.start()
    try:
        code = process.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        terminate_process_tree(process)
        code = 124
        output_lines.append(f"\ntimed_out=1\nerror=command timed out after {timeout} seconds\n")
    reader.join(timeout=5)
    elapsed = time.monotonic() - started
    output_lines.append(f"\nelapsed_seconds={elapsed:.1f}\n")
    return code, "".join(output_lines)


def git_value(*args: str) -> str:
    code, output = run(["git", *args], timeout=30)
    return output.strip() if code == 0 else ""


def parse_key_values(output: str) -> dict[str, str]:
    values: dict[str, str] = {}
    for line in output.splitlines():
        match = KEY_VALUE_RE.match(line.strip())
        if match:
            values[match.group(1)] = match.group(2)
    return values


def check_status(code: int, values: dict[str, str]) -> str:
    if code != 0:
        return "failed"
    issue_keys = [key for key in values if key.endswith("issues") or key.endswith("_issues")]
    if any(values.get(key) not in {"0", ""} for key in issue_keys):
        return "issues"
    if values.get("predeploy_checks") == "ok":
        return "ok"
    return "ok"


def render_section(name: str, code: int, values: dict[str, str]) -> list[str]:
    status = check_status(code, values)
    lines = [f"## {name}", "", f"- status: `{status}`"]
    important_keys = [
        "predeploy_checks",
        "generated_fresh_issues",
        "issues",
        "content_uniqueness_issues",
        "multilingual_route_issues",
        "guardian_conversion_issues",
        "affiliate_locale_issues",
        "accessibility_issues",
        "image_asset_issues",
        "performance_budget_issues",
        "runtime_performance_issues",
        "site_health_config_issues",
        "keyboard_navigation_issues",
        "tap_target_issues",
        "contrast_issues",
        "user_preference_issues",
        "storage_privacy_issues",
        "deploy_manifest_issues",
        "public_accessibility_issues",
        "public_asset_issues",
        "public_deploy_issues",
        "public_launch_link_issues",
        "public_launch_link_checked",
        "public_launch_link_profile_checked",
        "public_launch_link_shorts_checked",
        "public_launch_link_quiz_entries",
        "public_launch_link_safety_navs",
        "public_launch_link_utm_checks",
        "public_contact_issues",
        "public_discovery_issues",
        "public_external_link_issues",
        "public_garden_map_issues",
        "public_guide_issues",
        "public_guardian_issues",
        "public_header_issues",
        "public_home_issues",
        "public_indexability_issues",
        "public_internal_link_issues",
        "public_keepsake_issues",
        "public_locale_route_issues",
        "public_locale_issues",
        "public_luna_issues",
        "public_metadata_issues",
        "public_quiz_conversion_issues",
        "public_quiz_flow_issues",
        "public_quiz_issues",
        "public_revenue_path_issues",
        "public_repair_plan_issues",
        "public_schema_issues",
        "public_schema_url_issues",
        "public_sitemap_issues",
        "public_supply_issues",
        "public_not_found_issues",
        "public_visual_issues",
        "csp_runtime_issues",
        "public_trust_issues",
        "public_versioned_asset_issues",
        "promotion_platform_profile_setup_platforms",
        "promotion_platform_profile_setup_kpi_fields",
        "promotion_platform_profile_setup_issues",
        "promotion_platform_profile_setups_checked",
        "promotion_platform_profile_kpi_fields_checked",
        "public_promotion_kit_issues",
        "public_promotion_kit_campaigns_checked",
        "public_promotion_kit_tasks_checked",
        "public_promotion_kit_guardians_checked",
        "public_promotion_kit_scripts_checked",
        "public_promotion_kit_utm_contents_checked",
        "public_promotion_kit_kpi_fields_checked",
        "public_promotion_kit_measurement_rules_checked",
        "public_promotion_kit_revenue_bridge_kpis_checked",
        "public_promotion_kit_event_kpi_rows_checked",
        "public_promotion_kit_event_names_checked",
        "public_promotion_kit_monetization_bridges_checked",
        "public_promotion_kit_platform_profile_setups_checked",
        "public_promotion_kit_platform_profile_kpi_fields_checked",
        "public_promotion_kit_platform_profile_writeback_checked",
        "public_promotion_kit_platform_profile_verification_steps_checked",
        "public_promotion_kit_platform_profile_publish_gates_checked",
        "promotion_platform_profile_tracker_rows",
        "promotion_platform_profile_tracker_numeric_fields",
        "promotion_platform_profile_tracker_issues",
        "promotion_profile_writeback_rows",
        "promotion_profile_writeback_configured",
        "promotion_profile_writeback_issues",
        "promotion_profile_text_import_fields_parsed",
        "promotion_profile_text_import_has_profile_link",
        "promotion_profile_text_import_metric_fields_present",
        "promotion_profile_text_import_issues",
        "promotion_profile_setup_runbook_platforms",
        "promotion_profile_setup_runbook_configured",
        "promotion_profile_setup_runbook_pending",
        "promotion_profile_setup_runbook_clipboard_blocks",
        "promotion_profile_setup_runbook_issues",
        "promotion_profile_verification_platforms",
        "promotion_profile_verification_configured",
        "promotion_profile_verification_pending",
        "promotion_profile_verification_ready_to_publish",
        "promotion_profile_verification_issues",
        "promotion_profile_completion_configured",
        "promotion_profile_completion_expected",
        "promotion_profile_completion_evidence_required",
        "promotion_profile_completion_evidence_traceable",
        "promotion_profile_completion_evidence_issues",
        "promotion_profile_completion_packets_in_sync",
        "promotion_profile_completion_ready_to_publish",
        "promotion_profile_completion_blockers",
        "promotion_profile_completion_issues",
        "promotion_week_publication_runbook_week",
        "promotion_week_publication_runbook_tasks",
        "promotion_week_publication_runbook_scripts",
        "promotion_week_publication_runbook_platforms",
        "promotion_week_publication_runbook_ready_to_publish",
        "promotion_week_publication_runbook_issues",
        "promotion_platform_account_identity_platforms",
        "promotion_platform_account_identity_checks_per_platform",
        "promotion_platform_account_identity_rows",
        "promotion_platform_account_identity_pending",
        "promotion_platform_account_identity_configured",
        "promotion_platform_account_identity_issues",
        "promotion_profile_setup_action_rows",
        "promotion_profile_setup_action_ready_configure",
        "promotion_profile_setup_action_ready_writeback",
        "promotion_profile_setup_action_configured",
        "promotion_profile_setup_action_identity_checks",
        "promotion_profile_setup_action_evidence_checks",
        "promotion_profile_setup_action_gate_ready",
        "promotion_profile_setup_action_issues",
        "promotion_profile_link_readiness_rows",
        "promotion_profile_link_readiness_public_checked",
        "promotion_profile_link_readiness_public_ready",
        "promotion_profile_link_readiness_ready_configure",
        "promotion_profile_link_readiness_ready_writeback",
        "promotion_profile_link_readiness_configured",
        "promotion_profile_link_readiness_gate_ready",
        "promotion_profile_link_readiness_issues",
        "promotion_profile_proof_readiness_rows",
        "promotion_profile_proof_readiness_proof_files",
        "promotion_profile_proof_readiness_importable_templates",
        "promotion_profile_proof_readiness_public_ready",
        "promotion_profile_proof_readiness_configured",
        "promotion_profile_proof_readiness_ready_configure",
        "promotion_profile_proof_readiness_ready_writeback",
        "promotion_profile_proof_readiness_gate_ready",
        "promotion_profile_proof_readiness_issues",
        "promotion_first_batch_publish_action_rows",
        "promotion_first_batch_publish_action_ready",
        "promotion_first_batch_publish_action_blocked",
        "promotion_first_batch_publish_action_complete",
        "promotion_first_batch_publish_action_profile_public_ready",
        "promotion_first_batch_publish_action_profile_gate_ready",
        "promotion_first_batch_publish_action_issues",
        "promotion_first_batch_publish_readiness_rows",
        "promotion_first_batch_publish_readiness_profile_gate_ready",
        "promotion_first_batch_publish_readiness_asset_qa_ready",
        "promotion_first_batch_publish_readiness_ready_to_publish",
        "promotion_first_batch_publish_readiness_blocked",
        "promotion_first_batch_publish_readiness_published",
        "promotion_first_batch_publish_readiness_proof_files",
        "promotion_first_batch_publish_readiness_templates_safely_rejected",
        "promotion_first_batch_publish_readiness_issues",
        "promotion_first_batch_kpi_action_rows",
        "promotion_first_batch_kpi_action_ready",
        "promotion_first_batch_kpi_action_blocked",
        "promotion_first_batch_kpi_action_published",
        "promotion_first_batch_kpi_action_zero_source_rows",
        "promotion_first_batch_kpi_action_publish_ready",
        "promotion_first_batch_kpi_action_issues",
        "promotion_platform_kpi_tracker_rows",
        "promotion_platform_kpi_tracker_platforms",
        "promotion_platform_kpi_tracker_metric_fields",
        "promotion_platform_kpi_tracker_published_rows",
        "promotion_platform_kpi_tracker_filled_metric_rows",
        "promotion_platform_kpi_tracker_issues",
        "promotion_post_writeback_queue_rows",
        "promotion_post_writeback_published_rows",
        "promotion_post_writeback_issues",
        "promotion_post_text_import_fields_parsed",
        "promotion_post_text_import_has_post_url",
        "promotion_post_text_import_metric_fields_present",
        "promotion_post_text_import_issues",
        "promotion_placeholder_url_checked",
        "promotion_placeholder_url_rejected_by_validator",
        "promotion_placeholder_url_rejected_by_import",
        "promotion_placeholder_url_safe_validator_passed",
        "promotion_placeholder_url_safe_import_passed",
        "promotion_placeholder_url_docs_checked",
        "promotion_placeholder_url_doc_hits",
        "promotion_placeholder_url_safety_issues",
        "promotion_proof_note_generic_checked",
        "promotion_proof_note_generic_rejected",
        "promotion_proof_note_traceable_checked",
        "promotion_proof_note_traceable_accepted",
        "promotion_proof_note_profile_writeback_rejected",
        "promotion_proof_note_post_writeback_rejected",
        "promotion_proof_note_docs_checked",
        "promotion_proof_note_doc_hits",
        "promotion_proof_note_safety_issues",
        "promotion_evidence_ledger_rows",
        "promotion_evidence_ledger_required",
        "promotion_evidence_ledger_traceable",
        "promotion_evidence_ledger_generic",
        "promotion_evidence_ledger_missing",
        "promotion_evidence_ledger_pending",
        "promotion_evidence_ledger_issues",
        "promotion_first_batch_rows",
        "promotion_first_batch_published",
        "promotion_first_batch_pending",
        "promotion_first_batch_minimum_kpi_rows",
        "promotion_first_batch_ready_to_publish",
        "promotion_first_batch_weekly_decision_ready",
        "promotion_first_batch_issues",
        "promotion_first_batch_completion_rows",
        "promotion_first_batch_completion_published",
        "promotion_first_batch_completion_minimum_kpi_rows",
        "promotion_first_batch_completion_traceable_evidence",
        "promotion_first_batch_completion_generic_evidence",
        "promotion_first_batch_completion_missing_evidence",
        "promotion_first_batch_completion_ready_for_weekly",
        "promotion_first_batch_completion_blockers",
        "promotion_first_batch_completion_issues",
        "promotion_lead_demand_real_leads",
        "promotion_lead_demand_traceable_evidence",
        "promotion_lead_demand_explicit_consent",
        "promotion_lead_demand_matched_utm_rows",
        "promotion_lead_demand_repeated_routes",
        "promotion_lead_demand_ready_routes",
        "promotion_lead_demand_blockers",
        "promotion_lead_demand_issues",
        "promotion_lead_ops_action_rows",
        "promotion_lead_ops_action_real_leads",
        "promotion_lead_ops_action_template_rows",
        "promotion_lead_ops_action_blocked_rows",
        "promotion_lead_ops_action_waiting_rows",
        "promotion_lead_ops_action_ready_rows",
        "promotion_lead_ops_action_ready_routes",
        "promotion_lead_ops_action_repeated_routes",
        "promotion_lead_ops_action_story_assets",
        "promotion_lead_ops_action_issues",
        "promotion_master_stage",
        "promotion_master_stage_index",
        "promotion_master_profile_configured",
        "promotion_master_first_batch_published",
        "promotion_master_minimum_kpi_rows",
        "promotion_master_lead_ready_routes",
        "promotion_master_ready_offer_experiments",
        "promotion_master_command_ready_rows",
        "promotion_master_blocked_decisions",
        "promotion_master_issues",
        "promotion_stage_transition_rows",
        "promotion_stage_transition_complete",
        "promotion_stage_transition_current_blockers",
        "promotion_stage_transition_next_rows",
        "promotion_stage_transition_blocked_upstream",
        "promotion_stage_transition_command_ready",
        "promotion_stage_transition_empty_data",
        "promotion_stage_transition_issues",
        "promotion_profile_publish_handoff_rows",
        "promotion_profile_publish_handoff_complete",
        "promotion_profile_publish_handoff_current_blockers",
        "promotion_profile_publish_handoff_blocked_upstream",
        "promotion_profile_publish_handoff_ready_to_publish",
        "promotion_profile_publish_handoff_issues",
        "promotion_publish_kpi_handoff_rows",
        "promotion_publish_kpi_handoff_complete",
        "promotion_publish_kpi_handoff_current_blockers",
        "promotion_publish_kpi_handoff_blocked_upstream",
        "promotion_publish_kpi_handoff_published_rows",
        "promotion_publish_kpi_handoff_minimum_kpi_rows",
        "promotion_publish_kpi_handoff_ready_for_weekly",
        "promotion_publish_kpi_handoff_issues",
        "promotion_weekly_lead_offer_handoff_rows",
        "promotion_weekly_lead_offer_handoff_complete",
        "promotion_weekly_lead_offer_handoff_current_blockers",
        "promotion_weekly_lead_offer_handoff_blocked_upstream",
        "promotion_weekly_lead_offer_handoff_real_leads",
        "promotion_weekly_lead_offer_handoff_ready_routes",
        "promotion_weekly_lead_offer_handoff_public_free_ready",
        "promotion_weekly_lead_offer_handoff_ready_offers",
        "promotion_weekly_lead_offer_handoff_issues",
        "promotion_launch_ops_dashboard_rows",
        "promotion_launch_ops_dashboard_ready_areas",
        "promotion_launch_ops_dashboard_blocked_areas",
        "promotion_launch_ops_dashboard_hold_areas",
        "promotion_launch_ops_dashboard_profile_configured",
        "promotion_launch_ops_dashboard_first_batch_published",
        "promotion_launch_ops_dashboard_minimum_kpi_rows",
        "promotion_launch_ops_dashboard_lead_ready_routes",
        "promotion_launch_ops_dashboard_issues",
        "promotion_launch_day_run_rows",
        "promotion_launch_day_run_profile_rows",
        "promotion_launch_day_run_publish_rows",
        "promotion_launch_day_run_post_ops_rows",
        "promotion_launch_day_run_ready_rows",
        "promotion_launch_day_run_blocked_rows",
        "promotion_launch_day_run_dashboard_blocked_areas",
        "promotion_launch_day_run_issues",
        "promotion_launch_exception_rows",
        "promotion_launch_exception_stop_rows",
        "promotion_launch_exception_hold_rows",
        "promotion_launch_exception_escalate_rows",
        "promotion_launch_exception_profile_configured",
        "promotion_launch_exception_ready_to_publish",
        "promotion_launch_exception_first_batch_published",
        "promotion_launch_exception_empty_data_mode",
        "promotion_launch_exception_issues",
        "promotion_first_batch_asset_qa_rows",
        "promotion_first_batch_asset_qa_required_items",
        "promotion_first_batch_asset_qa_issues",
        "promotion_publishing_status_platform_tracker_rows",
        "promotion_publishing_status_platform_ready_rows",
        "promotion_publishing_status_platform_missing_rows",
        "promotion_publishing_status_platform_partial_rows",
        "promotion_publishing_status_platform_metric_rows",
        "promotion_writeback_issues",
        "promotion_writeback_stale_phrase_hits",
        "promotion_writeback_docs_with_platform_tracker",
        "promotion_launch_readiness_profile_rows",
        "promotion_launch_readiness_profile_links_valid",
        "promotion_launch_readiness_profile_configured",
        "promotion_launch_readiness_first_batch_rows",
        "promotion_launch_readiness_first_batch_scheduled",
        "promotion_launch_readiness_first_week_scheduled",
        "promotion_launch_readiness_asset_ready",
        "promotion_launch_readiness_published_rows",
        "promotion_launch_readiness_filled_kpi_rows",
        "promotion_launch_readiness_platform_checklist_rows",
        "promotion_launch_readiness_first_batch_schedule_rows",
        "promotion_launch_readiness_ready_to_start_setup",
        "promotion_launch_readiness_ready_to_publish",
        "promotion_launch_readiness_ready_for_kpi_decision",
        "promotion_launch_readiness_empty_data_mode",
        "promotion_launch_readiness_blockers",
        "promotion_launch_readiness_issues",
        "promotion_ops_closure_command_rows",
        "promotion_ops_closure_handoff_steps",
        "promotion_ops_closure_next_actions",
        "promotion_ops_closure_profile_platforms",
        "promotion_ops_closure_first_batch_rows",
        "promotion_ops_closure_ready_rows",
        "promotion_ops_closure_blocked_rows",
        "promotion_ops_closure_structured_imports",
        "promotion_ops_closure_issues",
        "promotion_operation_proof_profile_rows",
        "promotion_operation_proof_post_rows",
        "promotion_operation_proof_total_rows",
        "promotion_operation_proof_ready_to_publish",
        "promotion_operation_proof_issues",
        "promotion_operation_proof_templates_profile",
        "promotion_operation_proof_templates_post",
        "promotion_operation_proof_templates_files",
        "promotion_operation_proof_templates_profile_valid",
        "promotion_operation_proof_templates_post_safely_rejected",
        "promotion_operation_proof_templates_issues",
        "promotion_profile_evidence_checklist_platforms",
        "promotion_profile_evidence_checklist_rows",
        "promotion_profile_evidence_checklist_pending",
        "promotion_profile_evidence_checklist_issues",
        "promotion_first_batch_publish_checklist_tasks",
        "promotion_first_batch_publish_checklist_rows",
        "promotion_first_batch_publish_checklist_pre_publish",
        "promotion_first_batch_publish_checklist_post_publish",
        "promotion_first_batch_publish_checklist_pending",
        "promotion_first_batch_publish_checklist_issues",
        "promotion_first_batch_kpi_checklist_tasks",
        "promotion_first_batch_kpi_checklist_rows",
        "promotion_first_batch_kpi_checklist_zero_source_check",
        "promotion_first_batch_kpi_checklist_pending",
        "promotion_first_batch_kpi_checklist_issues",
        "promotion_profile_post_alignment_platforms",
        "promotion_profile_post_alignment_posts",
        "promotion_profile_post_alignment_rows",
        "promotion_profile_post_alignment_complete",
        "promotion_profile_post_alignment_pending",
        "promotion_profile_post_alignment_missing",
        "promotion_profile_post_alignment_unique_utm",
        "promotion_profile_post_alignment_unique_guardians",
        "promotion_profile_post_alignment_issues",
        "promotion_public_post_url_posts",
        "promotion_public_post_url_published",
        "promotion_public_post_url_rows",
        "promotion_public_post_url_pending_publish",
        "promotion_public_post_url_complete",
        "promotion_public_post_url_operator_verify",
        "promotion_public_post_url_missing",
        "promotion_public_post_url_issues",
        "promotion_zero_kpi_evidence_posts",
        "promotion_zero_kpi_evidence_published",
        "promotion_zero_kpi_evidence_rows",
        "promotion_zero_kpi_evidence_pending_publish",
        "promotion_zero_kpi_evidence_needs_source_proof",
        "promotion_zero_kpi_evidence_complete",
        "promotion_zero_kpi_evidence_missing",
        "promotion_zero_kpi_evidence_issues",
        "promotion_post_ops_readiness_rows",
        "promotion_post_ops_readiness_published",
        "promotion_post_ops_readiness_blocked",
        "promotion_post_ops_readiness_needs_public_verification",
        "promotion_post_ops_readiness_needs_kpi_source_proof",
        "promotion_post_ops_readiness_ready_weekly",
        "promotion_post_ops_readiness_public_pending_rows",
        "promotion_post_ops_readiness_zero_pending_rows",
        "promotion_post_ops_readiness_completion_ready",
        "promotion_post_ops_readiness_issues",
        "promotion_first_batch_evidence_rows",
        "promotion_first_batch_evidence_published",
        "promotion_first_batch_evidence_blocked_until_publish",
        "promotion_first_batch_evidence_needs_public_url",
        "promotion_first_batch_evidence_needs_kpi_source",
        "promotion_first_batch_evidence_needs_traceable_proof",
        "promotion_first_batch_evidence_ready_weekly",
        "promotion_first_batch_evidence_completion_ready",
        "promotion_first_batch_evidence_issues",
        "promotion_decision_readiness_rows",
        "promotion_decision_readiness_active_signal",
        "promotion_decision_readiness_ready",
        "promotion_decision_readiness_blocked",
        "promotion_decision_readiness_issues",
        "promotion_decision_input_rows",
        "promotion_decision_input_ready",
        "promotion_decision_input_active",
        "promotion_decision_input_blocked",
        "promotion_decision_input_input_rows",
        "promotion_decision_input_filled_rows",
        "promotion_decision_input_blocked_input_rows",
        "promotion_decision_input_lead_ready_routes",
        "promotion_decision_input_empty_data",
        "promotion_decision_input_issues",
        "promotion_launch_rehearsal_stage_rows",
        "promotion_launch_rehearsal_ready_stages",
        "promotion_launch_rehearsal_blocked_stages",
        "promotion_launch_rehearsal_profile_rows",
        "promotion_launch_rehearsal_post_rows",
        "promotion_launch_rehearsal_ready_to_publish",
        "promotion_launch_rehearsal_issues",
        "promotion_weekly_summary_profile_tracker_rows",
        "promotion_now_asset_briefs_count",
        "promotion_now_asset_briefs_platforms",
        "promotion_now_asset_briefs_scene_cards",
        "promotion_now_asset_briefs_issues",
        "humans_files_checked",
        "humans_sections_checked",
        "humans_snippets_checked",
        "humans_high_value_urls_checked",
        "humans_urls_checked",
        "commerce_catalogs_checked",
        "commerce_items_checked",
        "commerce_types_checked",
        "commerce_roles_checked",
        "commerce_free_keepsake_urls_checked",
        "commerce_owned_supply_urls_checked",
        "commerce_free_keepsake_guardians_checked",
        "commerce_owned_supply_guardians_checked",
        "commerce_owned_supply_contacts_checked",
        "commerce_affiliate_locale_policies_checked",
        "commerce_amazon_associate_tags_checked",
        "commerce_affiliate_asins_checked",
        "commerce_primary_affiliate_urls_checked",
        "commerce_affiliate_localized_urls_checked",
        "commerce_taiwan_affiliate_urls_checked",
        "commerce_luna_gumroad_urls_checked",
        "commerce_safety_boundaries_checked",
        "affiliate_zh_books_links_checked",
        "affiliate_non_zh_amazon_links_checked",
        "site_index_pages_checked",
        "site_index_languages_checked",
        "site_index_groups_checked",
        "site_index_core_flows_checked",
        "guardian_profiles_checked",
        "guardian_profile_love_languages_checked",
        "guardian_profile_assets_checked",
        "guardian_profile_routes_checked",
        "guardian_profile_guides_checked",
        "site_health_snapshots_checked",
        "site_health_coverage_fields_checked",
        "site_health_support_files_checked",
        "site_health_required_gates_checked",
        "site_health_primary_indexes_checked",
        "site_health_safety_boundaries_checked",
        "release_files_checked",
        "release_content_fields_checked",
        "release_public_indexes_checked",
        "release_verification_commands_checked",
        "release_required_outcomes_checked",
        "release_safety_boundaries_checked",
        "safety_index_files_checked",
        "safety_index_boundaries_checked",
        "safety_index_routes_checked",
        "safety_index_route_targets_checked",
        "safety_index_not_for_checked",
        "safety_index_first_steps_checked",
        "safety_index_first_step_urls_checked",
        "ai_discovery_files_checked",
        "ai_discovery_guidance_fields_checked",
        "ai_discovery_totals_checked",
        "ai_discovery_languages_checked",
        "ai_discovery_guardians_checked",
        "ai_discovery_core_concepts_checked",
        "ai_discovery_questions_checked",
        "ai_discovery_priority_urls_checked",
        "ai_discovery_discovery_files_checked",
        "discovery_cross_indexes_checked",
        "discovery_cross_index_urls_checked",
        "discovery_cross_index_targets_checked",
        "discovery_cross_index_fragments_checked",
        "discovery_cross_core_routes_checked",
        "Remote missing hashes",
        "Commit dirty",
        "pages",
        "indexable_pages",
        "sitemap_urls",
        "sitemap_alternates",
        "sitemap_hreflang_matches_checked",
        "affiliate_pages",
        "affiliate_links",
        "public_accessibility_pages_checked",
        "public_accessibility_links_checked",
        "public_accessibility_buttons_checked",
        "public_accessibility_images_checked",
        "public_accessibility_controls_checked",
        "public_accessibility_skip_links_checked",
        "public_accessibility_main_targets_checked",
        "public_accessibility_navs_checked",
        "public_accessibility_idrefs_checked",
        "public_accessibility_aria_current_checked",
        "public_asset_pages_checked",
        "public_asset_refs_seen",
        "public_asset_unique_assets_checked",
        "public_asset_immutable_assets_checked",
        "public_pages_checked",
        "public_external_links_checked",
        "public_affiliate_links_checked",
        "public_lang_checked",
        "public_canonicals_checked",
        "public_hreflang_sets_checked",
        "public_hreflang_links_checked",
        "public_jsonld_blocks_checked",
        "public_jsonld_entities_checked",
        "public_social_meta_checked",
        "public_social_images_checked",
        "public_social_immutable_images_checked",
        "public_current_asset_refs_checked",
        "public_versioned_asset_refs_checked",
        "public_quiz_data_asset_refs_checked",
        "public_immutable_assets_checked",
        "public_support_files_checked",
        "public_sitemap_urls_checked",
        "public_sitemap_alternates_checked",
        "public_sitemap_alternates_total",
        "public_robots_checked",
        "public_redirects_checked",
        "public_conversion_hrefs_checked",
        "public_anchor_targets_checked",
        "public_not_found_checked",
        "public_characters_universe_map_sections_checked",
        "public_characters_universe_map_cards_checked",
        "public_garden_map_sections_checked",
        "public_supply_starter_cards_checked",
        "public_contact_pages_checked",
        "public_contact_anchor_targets_checked",
        "public_contact_mailto_links_checked",
        "public_contact_mailto_bodies_checked",
        "public_contact_template_blocks_checked",
        "public_contact_template_buttons_checked",
        "public_contact_request_option_grids_checked",
        "public_contact_request_option_texts_checked",
        "public_contact_request_option_mailtos_checked",
        "public_contact_repair_option_mailtos_checked",
        "public_contact_protected_email_links_checked",
        "public_contact_source_routes_checked",
        "public_contact_saved_result_sections_checked",
        "public_contact_saved_result_actions_checked",
        "public_contact_saved_result_attribution_labels_checked",
        "public_contact_saved_result_attribution_fields_checked",
        "public_contact_quiz_data_refs_checked",
        "public_contact_subjects_checked",
        "public_contact_funnel_summary_sections_checked",
        "public_contact_funnel_summary_actions_checked",
        "public_contact_funnel_summary_context_labels_checked",
        "public_contact_funnel_summary_context_fields_checked",
        "public_contact_funnel_summary_empty_actions_checked",
        "public_discovery_feed_items",
        "public_discovery_feed_links_checked",
        "public_discovery_feed_item_metadata_checked",
        "public_discovery_feed_site_index_links_checked",
        "public_discovery_manifest_icons_checked",
        "public_discovery_manifest_icon_dimensions_checked",
        "public_discovery_manifest_shortcuts",
        "public_discovery_manifest_shortcut_links_checked",
        "public_discovery_manifest_expected_shortcuts_checked",
        "public_discovery_manifest_shortcut_icons_checked",
        "public_discovery_manifest_shortcut_icon_dimensions_checked",
        "public_discovery_manifest_screenshots_checked",
        "public_discovery_manifest_screenshot_dimensions_checked",
        "public_discovery_llms_sections_checked",
        "public_discovery_llms_snippets_checked",
        "public_discovery_llms_high_value_urls_checked",
        "public_discovery_llms_urls_checked",
        "public_discovery_llms_url_canonicals_checked",
        "public_discovery_text_files_checked",
        "public_discovery_security_fields_checked",
        "public_discovery_security_date_fields_checked",
        "public_discovery_humans_snippets_checked",
        "public_discovery_humans_urls_checked",
        "public_discovery_humans_site_index_urls_checked",
        "public_discovery_robots_lines_checked",
        "public_discovery_robots_sitemap_links_checked",
        "public_discovery_robots_sitemap_core_urls_checked",
        "public_support_sync_files_checked",
        "public_support_sync_json_files_checked",
        "public_support_sync_text_files_checked",
        "public_support_sync_xml_files_checked",
        "public_support_sync_bytes_checked",
        "public_support_sync_issues",
        "public_discovery_funnel_events_checked",
        "public_discovery_funnel_event_categories_checked",
        "public_discovery_funnel_event_roles_checked",
        "public_discovery_runtime_pack_events_checked",
        "public_discovery_promotion_event_kpi_rows_checked",
        "public_discovery_promotion_event_kpi_events_checked",
        "public_discovery_promotion_revenue_bridge_kpis_checked",
        "public_discovery_promotion_derived_rates_checked",
        "public_discovery_promotion_decision_rules_checked",
        "public_discovery_promotion_event_safety_fields_checked",
        "public_discovery_commerce_items_checked",
        "public_discovery_commerce_types_checked",
        "public_discovery_commerce_roles_checked",
        "public_discovery_commerce_free_keepsake_urls_checked",
        "public_discovery_commerce_owned_supply_urls_checked",
        "public_discovery_commerce_free_keepsake_guardians_checked",
        "public_discovery_commerce_owned_supply_guardians_checked",
        "public_discovery_commerce_owned_supply_contacts_checked",
        "public_discovery_commerce_affiliate_locale_policies_checked",
        "public_discovery_commerce_amazon_associate_tags_checked",
        "public_discovery_commerce_affiliate_asins_checked",
        "public_discovery_commerce_primary_affiliate_urls_checked",
        "public_discovery_commerce_affiliate_localized_urls_checked",
        "public_discovery_commerce_taiwan_affiliate_urls_checked",
        "public_discovery_commerce_luna_gumroad_urls_checked",
        "public_discovery_commerce_revenue_playbook_checked",
        "public_discovery_commerce_item_playbook_links_checked",
        "public_discovery_site_index_pages_checked",
        "public_discovery_site_index_languages_checked",
        "public_discovery_site_index_groups_checked",
        "public_discovery_site_index_flows_checked",
        "public_discovery_guardian_profiles_checked",
        "public_discovery_guardian_profile_routes_checked",
        "public_discovery_guardian_profile_assets_checked",
        "public_discovery_guardian_profile_guides_checked",
        "public_discovery_site_health_coverage_checked",
        "public_discovery_site_health_support_files_checked",
        "public_discovery_site_health_profile_smoke_counters_checked",
        "public_discovery_site_health_local_audit_groups_checked",
        "public_discovery_site_health_gates_checked",
        "public_discovery_site_health_indexes_checked",
        "public_discovery_release_content_checked",
        "public_discovery_release_profile_smoke_counters_checked",
        "public_discovery_release_local_audit_groups_checked",
        "public_discovery_release_indexes_checked",
        "public_discovery_release_commands_checked",
        "public_discovery_release_outcomes_checked",
        "public_discovery_safety_index_boundaries_checked",
        "public_discovery_safety_index_routes_checked",
        "public_discovery_safety_index_route_targets_checked",
        "public_discovery_safety_index_not_for_checked",
        "public_discovery_safety_index_steps_checked",
        "public_discovery_safety_index_first_step_urls_checked",
        "public_discovery_ai_guardians_checked",
        "public_discovery_ai_languages_checked",
        "public_discovery_ai_core_concepts_checked",
        "public_discovery_ai_questions_checked",
        "public_discovery_ai_priority_urls_checked",
        "public_discovery_ai_discovery_files_checked",
        "public_discovery_ai_guidance_fields_checked",
        "public_discovery_ai_profile_smoke_counters_checked",
        "public_discovery_cross_indexes_checked",
        "public_discovery_cross_index_urls_checked",
        "public_discovery_cross_index_targets_checked",
        "public_discovery_cross_index_fragments_checked",
        "public_discovery_cross_core_routes_checked",
        "public_external_unique_links_checked",
        "public_external_hosts_checked",
        "public_external_anchors_checked",
        "public_external_blank_target_rel_checked",
        "public_external_affiliate_links_checked",
        "public_external_affiliate_anchors_checked",
        "public_external_affiliate_zh_books_links_checked",
        "public_external_affiliate_non_zh_amazon_links_checked",
        "public_external_affiliate_disclosure_pages_checked",
        "public_garden_map_pages_checked",
        "public_garden_map_quiz_scripts_checked",
        "public_garden_map_hero_actions_checked",
        "public_garden_map_saved_templates_checked",
        "public_garden_map_saved_actions_checked",
        "public_garden_map_handoff_cards_checked",
        "public_garden_map_route_cards_checked",
        "public_garden_map_tool_cards_checked",
        "public_garden_map_guardian_cards_checked",
        "public_garden_map_guide_cards_checked",
        "public_garden_map_trust_cards_checked",
        "public_garden_map_boundary_sections_checked",
        "public_guide_index_pages_checked",
        "public_guide_index_actions_checked",
        "public_guide_index_action_events_checked",
        "public_guide_index_compass_cards_checked",
        "public_guide_index_compass_events_checked",
        "public_guide_index_domain_cards_checked",
        "public_guide_index_domain_actions_checked",
        "public_guide_index_domain_events_checked",
        "public_guide_index_cards_checked",
        "public_guide_index_boundary_sections_checked",
        "public_guide_pages_checked",
        "public_guide_quiz_scripts_checked",
        "public_guide_resume_templates_checked",
        "public_guide_resume_events_checked",
        "public_guide_article_sections_checked",
        "public_guide_safety_callouts_checked",
        "public_guide_related_cards_checked",
        "public_guide_action_bridges_checked",
        "public_guide_action_cards_checked",
        "public_guide_action_events_checked",
        "public_guide_guardian_links_checked",
        "public_guide_supply_links_checked",
        "public_guide_repair_links_checked",
        "public_guide_luna_links_checked",
        "public_guide_anchor_targets_checked",
        "public_guardian_overview_pages_checked",
        "public_guardian_overview_map_cards_checked",
        "public_guardian_overview_map_events_checked",
        "public_guardian_overview_need_cards_checked",
        "public_guardian_overview_need_events_checked",
        "public_guardian_overview_entry_actions_checked",
        "public_guardian_overview_entry_events_checked",
        "public_guardian_pages_checked",
        "public_guardian_domain_markers_checked",
        "public_guardian_hero_supply_links_checked",
        "public_guardian_hero_events_checked",
        "public_guardian_route_snapshots_checked",
        "public_guardian_route_snapshot_events_checked",
        "public_guardian_guide_links_checked",
        "public_guardian_repair_links_checked",
        "public_guardian_supply_links_checked",
        "public_guardian_luna_links_checked",
        "public_guardian_affiliate_links_checked",
        "public_guardian_affiliate_zh_books_links_checked",
        "public_guardian_affiliate_non_zh_amazon_links_checked",
        "public_guardian_keepsake_links_checked",
        "public_guardian_request_mailtos_checked",
        "public_guardian_supply_panel_events_checked",
        "public_guardian_nav_cards_checked",
        "public_guardian_nav_events_checked",
        "public_guardian_resume_templates_checked",
        "public_guardian_resume_events_checked",
        "public_header_cases_checked",
        "public_header_core_html_cases_checked",
        "public_header_csp_tokens_checked",
        "public_home_pages_checked",
        "public_home_quiz_scripts_checked",
        "public_home_quiz_questions_checked",
        "public_home_quiz_results_checked",
        "public_home_quiz_labels_checked",
        "public_home_quiz_roots_checked",
        "public_home_quiz_start_buttons_checked",
        "public_home_saved_templates_checked",
        "public_home_saved_actions_checked",
        "public_home_saved_funnel_events_checked",
        "public_home_universe_gate_sections_checked",
        "public_home_universe_gate_cards_checked",
        "public_home_journey_sections_checked",
        "public_home_journey_cards_checked",
        "public_home_safety_sections_checked",
        "public_home_safety_links_checked",
        "public_home_hero_ctas_checked",
        "public_indexability_sitemap_urls_listed",
        "public_indexability_sitemap_pages_checked",
        "public_indexability_noindex_pages_checked",
        "public_indexability_redirects_checked",
        "public_indexability_sitemap_absence_checked",
        "public_internal_link_pages_checked",
        "public_internal_links_seen",
        "public_internal_unique_links_checked",
        "public_internal_html_targets_checked",
        "public_internal_canonical_targets_checked",
        "public_internal_anchor_targets_checked",
        "public_internal_redirects_followed",
        "public_keepsake_pages_checked",
        "public_keepsake_shelf_cards_checked",
        "public_keepsake_collector_cards_checked",
        "public_keepsake_story_images_checked",
        "public_keepsake_download_links_checked",
        "public_keepsake_collector_open_events_checked",
        "public_keepsake_collector_download_events_checked",
        "public_keepsake_story_buttons_checked",
        "public_keepsake_route_links_checked",
        "public_keepsake_plan_links_checked",
        "public_keepsake_practice_cards_checked",
        "public_keepsake_practice_plan_links_checked",
        "public_keepsake_practice_route_links_checked",
        "public_keepsake_practice_print_buttons_checked",
        "public_keepsake_free_asset_cards_checked",
        "public_keepsake_free_asset_events_checked",
        "public_keepsake_free_asset_request_mailtos_checked",
        "public_keepsake_collector_request_mailtos_checked",
        "public_keepsake_safety_bridge_sections_checked",
        "public_keepsake_safety_bridge_links_checked",
        "public_keepsake_waitlist_cards_checked",
        "public_keepsake_waitlist_mailtos_checked",
        "public_keepsake_waitlist_option_mailtos_checked",
        "public_keepsake_waitlist_copy_buttons_checked",
        "public_locale_route_pages_checked",
        "public_locale_route_primary_nav_links_checked",
        "public_locale_route_footer_links_checked",
        "public_locale_route_language_links_checked",
        "public_locale_route_language_matches_checked",
        "public_locale_route_nav_matches_checked",
        "public_locale_route_footer_matches_checked",
        "public_locale_route_footer_exact_pages_checked",
        "public_locale_pages_checked",
        "public_locale_nav_labels_checked",
        "public_locale_footer_labels_checked",
        "public_locale_language_menu_labels_checked",
        "public_locale_active_language_links_checked",
        "public_luna_pages_checked",
        "public_luna_alias_redirects_checked",
        "public_luna_protocol_cards_checked",
        "public_luna_use_cases_checked",
        "public_luna_offer_cards_checked",
        "public_luna_guardian_cards_checked",
        "public_luna_guardian_repair_links_checked",
        "public_luna_guardian_supply_links_checked",
        "public_luna_hero_ctas_checked",
        "public_luna_starter_sections_checked",
        "public_luna_starter_ctas_checked",
        "public_luna_use_case_ctas_checked",
        "public_luna_offer_ctas_checked",
        "public_luna_product_pack_cards_checked",
        "public_luna_product_pack_ctas_checked",
        "public_luna_resume_templates_checked",
        "public_metadata_pages_checked",
        "public_metadata_social_cards_checked",
        "public_metadata_hreflang_links_checked",
        "public_metadata_jsonld_blocks_checked",
        "public_metadata_images_checked",
        "public_metadata_image_dimensions_checked",
        "public_metadata_app_meta_pages_checked",
        "public_quiz_conversion_assets_checked",
        "public_quiz_conversion_results_checked",
        "public_quiz_conversion_internal_urls_checked",
        "public_quiz_conversion_anchor_targets_checked",
        "public_quiz_conversion_images_checked",
        "public_quiz_conversion_affiliate_links_checked",
        "public_quiz_conversion_pass_fields_checked",
        "public_quiz_conversion_home_saved_template_checks",
        "public_quiz_conversion_resume_template_pages_checked",
        "public_quiz_conversion_resume_template_checks",
        "public_quiz_flow_cases_checked",
        "public_quiz_flow_results_checked",
        "public_quiz_flow_ctas_checked",
        "public_quiz_flow_funnel_events_checked",
        "public_quiz_flow_affiliate_links_checked",
        "public_quiz_flow_attributions_checked",
        "public_quiz_flow_disclosures_checked",
        "public_revenue_path_pages_checked",
        "public_revenue_path_quiz_assets_checked",
        "public_revenue_path_results_checked",
        "public_revenue_path_result_url_fields_checked",
        "public_revenue_path_result_text_fields_checked",
        "public_revenue_path_internal_targets_checked",
        "public_revenue_path_affiliate_links_checked",
        "public_revenue_path_starter_kits_checked",
        "public_revenue_path_supply_product_packs_checked",
        "public_revenue_path_luna_pages_checked",
        "public_revenue_path_luna_product_links_checked",
        "public_revenue_path_luna_product_slugs_checked",
        "public_revenue_path_funnel_revenue_events_checked",
        "public_quiz_assets_checked",
        "public_quiz_questions_checked",
        "public_quiz_results_checked",
        "public_quiz_guide_urls_checked",
        "public_quiz_story_images_checked",
        "public_quiz_story_ctas_checked",
        "public_quiz_starter_steps_checked",
        "public_repair_plan_pages_checked",
        "public_repair_plan_hero_events_checked",
        "public_repair_plan_day_cards_checked",
        "public_repair_plan_worksheet_fields_checked",
        "public_repair_plan_worksheet_actions_checked",
        "public_repair_plan_asset_sections_checked",
        "public_repair_plan_asset_cards_checked",
        "public_repair_plan_asset_links_checked",
        "public_repair_plan_asset_events_checked",
        "public_repair_plan_guardian_cards_checked",
        "public_repair_plan_guardian_action_events_checked",
        "public_repair_plan_guardian_supply_links_checked",
        "public_repair_plan_guardian_character_links_checked",
        "public_repair_plan_guardian_luna_links_checked",
        "public_repair_plan_guardian_affiliate_links_checked",
        "public_repair_plan_guardian_affiliate_zh_books_links_checked",
        "public_repair_plan_guardian_affiliate_non_zh_amazon_links_checked",
        "public_repair_plan_resume_templates_checked",
        "public_repair_plan_resume_events_checked",
        "public_repair_plan_safety_sections_checked",
        "public_schema_pages_checked",
        "public_schema_jsonld_blocks_checked",
        "public_schema_organization_entities_checked",
        "public_schema_primary_entities_checked",
        "public_schema_date_modified_entities_checked",
        "public_schema_breadcrumb_entities_checked",
        "public_schema_article_entities_checked",
        "public_schema_howto_entities_checked",
        "public_schema_itemlist_entities_checked",
        "public_schema_core_page_types_checked",
        "public_schema_guardian_profile_types_checked",
        "public_schema_url_pages_checked",
        "public_schema_url_jsonld_blocks_checked",
        "public_schema_url_values_checked",
        "public_schema_url_internal_urls_checked",
        "public_schema_url_image_urls_checked",
        "public_schema_url_external_urls_checked",
        "public_schema_url_sitemap_page_urls_checked",
        "public_schema_url_unique_targets_checked",
        "public_sitemap_pages_checked",
        "public_sitemap_urls_listed",
        "public_sitemap_core_universe_routes_expected",
        "public_sitemap_core_universe_routes_checked",
        "public_sitemap_lastmod_checked",
        "public_sitemap_changefreq_checked",
        "public_sitemap_priority_checked",
        "public_sitemap_site_index_pages_checked",
        "public_sitemap_site_index_canonical_matches_checked",
        "public_sitemap_hreflang_links_checked",
        "public_supply_pages_checked",
        "public_supply_hero_events_checked",
        "public_supply_entry_events_checked",
        "public_supply_quick_cards_checked",
        "public_supply_quick_events_checked",
        "public_supply_route_cards_checked",
        "public_supply_route_action_events_checked",
        "public_supply_guide_links_checked",
        "public_supply_luna_links_checked",
        "public_supply_route_request_mailtos_checked",
        "public_supply_route_product_stacks_checked",
        "public_supply_route_product_links_checked",
        "public_supply_route_product_events_checked",
        "public_supply_copy_buttons_checked",
        "public_supply_affiliate_links_checked",
        "public_supply_affiliate_zh_books_links_checked",
        "public_supply_affiliate_non_zh_amazon_links_checked",
        "public_supply_affiliate_book_cards_checked",
        "public_supply_affiliate_route_tags_checked",
        "public_supply_wishlist_cards_checked",
        "public_supply_wishlist_formats_checked",
        "public_supply_wishlist_mailtos_checked",
        "public_supply_wishlist_copy_buttons_checked",
        "public_supply_decision_sections_checked",
        "public_supply_decision_cards_checked",
        "public_supply_decision_links_checked",
        "public_supply_safety_sections_checked",
        "public_supply_safety_bridge_sections_checked",
        "public_supply_safety_bridge_links_checked",
        "public_not_found_cases_checked",
        "public_not_found_localized_cases",
        "public_not_found_safe_route_links_checked",
        "public_visual_attempts",
        "public_visual_cases_checked",
        "public_visual_screenshots",
        "public_visual_quiz_flow_cases",
        "public_visual_conversion_cases",
        "public_visual_garden_map_cases",
        "public_visual_language_menu_cases",
        "public_visual_redirect_cases",
        "public_visual_worksheet_cases",
        "public_visual_copy_cases",
        "public_visual_anchor_focus_cases",
        "public_visual_saved_resume_cases",
        "public_visual_horizontal_overflow_issues",
        "public_visual_console_error_cases",
        "public_visual_page_error_cases",
        "public_visual_parse_error",
        "public_visual_stderr_tail",
        "public_visual_stdout_tail",
        "csp_runtime_pages_checked",
        "csp_runtime_violations",
        "public_trust_pages_checked",
        "public_trust_boundary_texts_checked",
        "public_trust_policy_compass_cards_checked",
        "public_trust_policy_detail_cards_checked",
        "public_trust_about_garden_pass_cards_checked",
        "public_trust_about_hero_actions_checked",
        "public_trust_about_hero_events_checked",
        "public_trust_about_cards_checked",
        "public_trust_theory_domain_cards_checked",
        "public_trust_theory_domain_events_checked",
        "public_trust_theory_guardian_cards_checked",
        "public_trust_theory_faq_cards_checked",
        "public_trust_theory_hero_actions_checked",
        "public_trust_theory_hero_events_checked",
        "public_trust_about_theory_distinction_checks",
        "public_trust_action_routes_checked",
        "public_trust_action_events_checked",
        "public_trust_contact_route_anchors_checked",
        "public_trust_contact_funnel_mailtos_checked",
        "public_trust_noncommercial_pages_checked",
        "public_versioned_asset_pages_checked",
        "public_versioned_asset_css_refs_checked",
        "public_versioned_asset_interaction_refs_checked",
        "public_versioned_asset_affiliate_refs_checked",
        "public_versioned_asset_quiz_data_refs_checked",
        "public_versioned_asset_root_refs_checked",
        "public_versioned_asset_stale_refs",
        "runtime_performance_pages_checked",
        "runtime_performance_attempts",
        "runtime_performance_worst_lcp_ms",
        "runtime_performance_worst_cls",
        "runtime_performance_max_transfer_bytes",
        "keyboard_navigation_cases_checked",
        "keyboard_navigation_tab_stops_checked",
        "keyboard_navigation_named_focuses_checked",
        "tap_target_pages_checked",
        "tap_targets_checked",
        "contrast_pages_checked",
        "contrast_text_nodes_checked",
        "user_preference_pages_checked",
        "user_preference_checks",
        "storage_privacy_checks",
        "storage_privacy_local_keys_checked",
        "internal_refs",
        "external_links",
        "anchor_accessible_names",
        "primary_nav_links",
        "footer_guardian_links",
        "language_menu_links",
        "language_hreflang_matches",
        "canonical_links",
        "hreflang_links",
        "jsonld_blocks",
        "primary_jsonld_entities",
        "core_page_schema_types_checked",
        "guardian_profile_schema_types_checked",
        "social_cards",
        "social_locale_tags",
        "mailto_links",
        "funnel_event_catalogs_checked",
        "funnel_events_checked",
        "funnel_event_categories_checked",
        "funnel_event_roles_checked",
        "funnel_markup_actions_checked",
        "funnel_markup_event_names_checked",
        "funnel_dynamic_templates_checked",
        "funnel_dynamic_template_events_checked",
        "funnel_markup_mailtos_checked",
        "funnel_markup_luna_products_checked",
        "funnel_markup_copy_actions_checked",
        "funnel_markup_story_actions_checked",
        "promotion_event_kpi_rows_checked",
        "promotion_event_kpi_events_checked",
        "promotion_publish_pack_week",
        "promotion_publish_pack_weeks",
        "promotion_publish_pack_tasks",
        "promotion_publish_pack_issues",
        "promotion_kpi_tracker_rows",
        "promotion_kpi_tracker_fields",
        "promotion_kpi_tracker_issues",
        "promotion_metric_source_rows",
        "promotion_metric_source_platform_fields",
        "promotion_metric_source_site_conversion_fields",
        "promotion_metric_source_route_interest_fields",
        "promotion_metric_source_lead_intent_fields",
        "promotion_metric_source_issues",
        "promotion_data_collection_sources",
        "promotion_data_collection_rows",
        "promotion_data_collection_profile_rows",
        "promotion_data_collection_shorts_rows",
        "promotion_data_collection_minimum_kpi_rows",
        "promotion_data_collection_lead_intent_rows",
        "promotion_data_collection_blocked_rows",
        "promotion_data_collection_ready_rows",
        "promotion_data_collection_filled_rows",
        "promotion_data_collection_issues",
        "promotion_kpi_schema_fields",
        "promotion_kpi_schema_post_metrics",
        "promotion_kpi_schema_profile_metrics",
        "promotion_kpi_schema_event_kpis",
        "promotion_kpi_schema_event_names",
        "promotion_kpi_schema_catalog_events",
        "promotion_kpi_schema_revenue_bridge_kpis",
        "promotion_kpi_schema_commerce_items",
        "promotion_kpi_schema_commerce_playbooks",
        "promotion_kpi_schema_attribution_rows",
        "promotion_kpi_schema_issues",
        "promotion_posting_queue_platforms",
        "promotion_posting_queue_rows",
        "promotion_posting_queue_start_date",
        "promotion_posting_queue_issues",
        "promotion_publishing_status_queue_rows",
        "promotion_publishing_status_tracker_rows",
        "promotion_publishing_status_platforms",
        "promotion_publishing_status_published_scripts",
        "promotion_publishing_status_ready",
        "promotion_publishing_status_warnings",
        "promotion_publishing_status_issues",
        "promotion_kpi_writeback_posting_rows",
        "promotion_kpi_writeback_platform_rows",
        "promotion_kpi_writeback_script_rows",
        "promotion_kpi_writeback_published_rows",
        "promotion_kpi_writeback_filled_script_rows",
        "promotion_kpi_writeback_attribution_filled_rows",
        "promotion_kpi_writeback_rollup_scripts",
        "promotion_kpi_writeback_consistency_issues",
        "promotion_launch_brief_weeks",
        "promotion_launch_brief_week",
        "promotion_launch_brief_rows",
        "promotion_launch_brief_scripts",
        "promotion_launch_brief_platforms",
        "promotion_launch_brief_warnings",
        "promotion_launch_brief_issues",
        "promotion_revenue_decision_guardians",
        "promotion_revenue_decision_filled_rows",
        "promotion_revenue_decision_profile_filled_rows",
        "promotion_revenue_decision_profile_stage",
        "promotion_revenue_decision_empty_data_mode",
        "promotion_revenue_decision_issues",
        "promotion_week_decision_gate_weekly",
        "promotion_week_decision_gate_scale",
        "promotion_week_decision_gate_owned",
        "promotion_week_decision_gate_offer",
        "promotion_week_decision_gate_blockers",
        "promotion_week_decision_gate_issues",
        "promotion_lead_intake_guardians",
        "promotion_lead_intake_template_rows",
        "promotion_lead_intake_types",
        "promotion_lead_intake_source_options",
        "promotion_lead_intake_kpi_mappings",
        "promotion_lead_intake_issues",
        "promotion_lead_form_configured_forms",
        "promotion_lead_form_rendered_forms",
        "promotion_lead_form_rendered_send_events",
        "promotion_lead_form_rendered_copy_events",
        "promotion_lead_form_rendered_required_fields",
        "promotion_lead_form_rendered_guardian_options",
        "promotion_lead_form_rendered_intake_options",
        "promotion_lead_form_tracker_fields",
        "promotion_lead_form_intake_types",
        "promotion_lead_form_source_options",
        "promotion_lead_form_issues",
        "promotion_lead_form_import_languages",
        "promotion_lead_form_import_sources",
        "promotion_lead_form_import_checked_texts",
        "promotion_lead_form_import_valid_texts",
        "promotion_lead_form_import_issues",
        "promotion_lead_text_import_fields_parsed",
        "promotion_lead_text_import_has_reply_email",
        "promotion_lead_text_import_has_utm_content",
        "promotion_lead_text_import_issues",
        "promotion_lead_writeback_rows",
        "promotion_lead_writeback_template_rows",
        "promotion_lead_writeback_real_rows",
        "promotion_lead_writeback_issues",
        "promotion_lead_request_proof_rows",
        "promotion_lead_request_proof_files",
        "promotion_lead_request_proof_guardians",
        "promotion_lead_request_proof_intake_types",
        "promotion_lead_request_proof_safe_rejected",
        "promotion_lead_request_proof_real_leads",
        "promotion_lead_request_proof_issues",
        "promotion_lead_evidence_lead_rows",
        "promotion_lead_evidence_real_rows",
        "promotion_lead_evidence_checks_per_lead",
        "promotion_lead_evidence_checklist_rows",
        "promotion_lead_evidence_pending_template_rows",
        "promotion_lead_evidence_missing_rows",
        "promotion_lead_evidence_issues",
        "promotion_lead_magnet_inventory_languages",
        "promotion_lead_magnet_inventory_guardians",
        "promotion_lead_magnet_inventory_story_assets",
        "promotion_lead_magnet_inventory_expected_story_assets",
        "promotion_lead_magnet_inventory_issues",
        "promotion_offer_hypothesis_rows",
        "promotion_offer_hypothesis_ready",
        "promotion_offer_hypothesis_hold",
        "promotion_offer_hypothesis_blockers",
        "promotion_offer_hypothesis_issues",
        "promotion_offer_experiment_rows",
        "promotion_offer_experiment_ready",
        "promotion_offer_experiment_hold",
        "promotion_offer_experiment_blockers",
        "promotion_offer_experiment_issues",
        "promotion_offer_experiment_queue_rows",
        "promotion_offer_experiment_queue_ready",
        "promotion_offer_experiment_queue_waiting",
        "promotion_offer_experiment_queue_blocked",
        "promotion_offer_experiment_queue_issues",
        "promotion_asset_backlog_guardians",
        "promotion_asset_backlog_items",
        "promotion_asset_backlog_now",
        "promotion_asset_backlog_later",
        "promotion_asset_backlog_issues",
        "promotion_asset_fulfillment_rows",
        "promotion_asset_fulfillment_ready_to_prepare",
        "promotion_asset_fulfillment_public_free_ready",
        "promotion_asset_fulfillment_ready_after_real_request",
        "promotion_asset_fulfillment_ready_after_offer_gate",
        "promotion_asset_fulfillment_blocked_until_real_request",
        "promotion_asset_fulfillment_blocked_until_offer_ready",
        "promotion_asset_fulfillment_real_leads",
        "promotion_asset_fulfillment_ready_offer_assets",
        "promotion_asset_fulfillment_issues",
        "promotion_asset_commerce_guardians",
        "promotion_asset_commerce_pairs",
        "promotion_asset_commerce_backlog_items",
        "promotion_asset_commerce_backlog_links",
        "promotion_asset_commerce_lead_magnet_links",
        "promotion_asset_commerce_experiment_links",
        "promotion_asset_commerce_anchor_checks",
        "promotion_asset_commerce_issues",
        "promotion_trust_safety_boundaries",
        "promotion_trust_safety_routes_checked",
        "promotion_trust_safety_snippet_checks",
        "promotion_trust_commerce_items",
        "promotion_trust_commerce_playbook_checks",
        "promotion_trust_commerce_item_checks",
        "promotion_trust_commerce_local_url_checks",
        "promotion_trust_pages_checked",
        "promotion_trust_page_snippet_checks",
        "promotion_trust_external_commercial_links",
        "promotion_trust_commerce_safety_issues",
        "promotion_now_asset_pack_scripts",
        "promotion_now_asset_pack_guardians",
        "promotion_now_asset_pack_issues",
        "promotion_now_asset_queue_scripts",
        "promotion_now_asset_queue_steps",
        "promotion_now_asset_queue_rows",
        "promotion_now_asset_queue_issues",
        "promotion_week_asset_briefs_weeks",
        "promotion_week_asset_briefs_count",
        "promotion_week_asset_briefs_scene_cards",
        "promotion_week_asset_briefs_platform_captions",
        "promotion_week_asset_briefs_issues",
        "promotion_launch_command_rows",
        "promotion_launch_command_ready",
        "promotion_launch_command_blocked",
        "promotion_launch_command_profile_rows",
        "promotion_launch_command_publish_rows",
        "promotion_launch_command_issues",
        "promotion_attribution_reconciliation_rows",
        "promotion_attribution_reconciliation_profile_rows",
        "promotion_attribution_reconciliation_shorts_rows",
        "promotion_attribution_reconciliation_kpi_rows",
        "promotion_attribution_reconciliation_filled_kpi_rows",
        "promotion_attribution_reconciliation_issues",
        "promotion_launch_link_rows",
        "promotion_launch_link_profile",
        "promotion_launch_link_shorts",
        "promotion_launch_link_issues",
        "promotion_execution_sheet_weeks",
        "promotion_execution_sheet_profile_gates",
        "promotion_execution_sheet_profile_pending",
        "promotion_execution_sheet_platform_posts",
        "promotion_execution_sheet_scripts",
        "promotion_execution_sheet_issues",
        "promotion_spreadsheet_sheets",
        "promotion_spreadsheet_rendered_sheets",
        "promotion_next_actions_selected_tasks",
        "promotion_next_actions_actions",
        "promotion_next_actions_profile_actions",
        "promotion_next_actions_profile_pending_rows",
        "promotion_next_actions_empty_data_mode",
        "promotion_next_actions_issues",
        "promotion_weekly_summary_tracker_rows",
        "promotion_weekly_summary_recommendations",
        "promotion_weekly_summary_empty_data_mode",
        "promotion_weekly_summary_issues",
        "promotion_weekly_review_ready",
        "promotion_weekly_review_empty_data",
        "promotion_weekly_review_first_batch_rows",
        "promotion_weekly_review_first_batch_published",
        "promotion_weekly_review_minimum_kpi_rows",
        "promotion_weekly_review_hold_reasons",
        "promotion_weekly_review_issues",
        "promotion_weekly_review_action_rows",
        "promotion_weekly_review_action_ready_rows",
        "promotion_weekly_review_action_blocked_rows",
        "promotion_weekly_review_action_hold_rows",
        "promotion_weekly_review_action_weekly_ready",
        "promotion_weekly_review_action_empty_data",
        "promotion_weekly_review_action_evidence_pending",
        "promotion_weekly_review_action_evidence_complete",
        "promotion_weekly_review_action_issues",
        "promotion_weekly_decision_evidence_rows",
        "promotion_weekly_decision_evidence_complete",
        "promotion_weekly_decision_evidence_pending",
        "promotion_weekly_decision_evidence_weekly_ready",
        "promotion_weekly_decision_evidence_decision_ready",
        "promotion_weekly_decision_evidence_empty_data",
        "promotion_weekly_decision_evidence_issues",
        "promotion_blocker_resolution_rows",
        "promotion_blocker_resolution_active",
        "promotion_blocker_resolution_ready_now",
        "promotion_blocker_resolution_profile_rows",
        "promotion_blocker_resolution_publish_rows",
        "promotion_blocker_resolution_decision_rows",
        "promotion_blocker_resolution_lead_rows",
        "promotion_blocker_resolution_offer_rows",
        "promotion_blocker_resolution_empty_data",
        "promotion_blocker_resolution_issues",
        "promotion_operator_handoff_steps",
        "promotion_operator_handoff_ready",
        "promotion_operator_handoff_blocked",
        "promotion_operator_handoff_profile_pending",
        "promotion_operator_handoff_first_batch_pending",
        "promotion_operator_handoff_weekly_ready",
        "promotion_operator_handoff_issues",
        "promotion_operator_import_templates",
        "promotion_operator_import_expected_templates",
        "promotion_operator_import_checked_templates",
        "promotion_operator_import_valid_templates",
        "promotion_operator_import_template_issues",
        "promotion_empty_data_safety_empty_mode",
        "promotion_empty_data_safety_fail_closed_checks",
        "promotion_empty_data_safety_blocked_offer_rows",
        "promotion_empty_data_safety_blocked_experiment_rows",
        "promotion_empty_data_safety_issues",
        "promotion_daily_ops_expected_date",
        "promotion_daily_ops_target_files",
        "promotion_daily_ops_missing_docs",
        "promotion_daily_ops_stale_docs",
        "promotion_daily_ops_stale_commands",
        "promotion_daily_ops_refreshed",
        "promotion_daily_ops_issues",
        "promotion_decision_scenarios_checked",
        "promotion_decision_profile_scenarios_checked",
        "promotion_decision_scenario_issues",
        "home_quiz_entry_pages",
        "guide_action_bridge_pages",
        "guide_focus_article_pages",
        "guide_boilerplate_free_pages",
        "legacy_guide_focus_article_pages",
        "legacy_guide_boilerplate_free_pages",
        "character_result_resume_pages",
        "resources_supply_entry_pages",
        "trust_action_route_pages",
        "current_css_asset_refs",
        "current_interaction_asset_refs",
        "current_affiliate_asset_refs",
        "current_quiz_data_asset_refs",
        "image_assets_checked",
        "priority_images_checked",
        "image_preloads_checked",
        "deploy_manifest_files",
        "deploy_manifest_required_files",
        "deploy_manifest_declared_files",
        "deploy_manifest_missing_declared_required_files",
        "deploy_manifest_special_files",
        "deploy_manifest_special_upload_files",
        "site_health_config_checks",
        "site_health_config_check_tuples_parsed",
        "site_health_config_commands",
        "site_health_config_scripts",
        "site_health_config_python_scripts_compiled",
        "site_health_config_node_scripts",
        "site_health_config_node_scripts_checked",
        "site_health_config_node_missing",
        "site_health_config_important_keys",
        "site_health_config_retry_names",
        "site_health_config_predeploy_scripts",
        "site_health_config_predeploy_python_scripts_compiled",
        "site_health_config_missing_predeploy_scripts",
        "site_health_config_release_verification_scripts",
        "site_health_config_missing_release_verification_scripts",
        "site_health_config_release_local_audit_scripts",
        "site_health_config_missing_release_local_audit_scripts",
        "site_health_config_site_health_local_audit_scripts",
        "site_health_config_unknown_site_health_local_audits",
        "site_health_config_missing_site_health_local_audit_scripts",
        "site_health_config_site_health_release_local_audit_mismatches",
        "site_health_config_issue_metric_keys",
        "site_health_config_duplicate_check_names",
        "site_health_config_duplicate_check_commands",
        "site_health_config_duplicate_script_paths",
        "site_health_config_missing_scripts",
        "site_health_config_duplicate_important_keys",
        "site_health_config_unknown_retry_names",
        "site_health_config_missing_issue_important_keys",
        "site_health_config_malformed_checks",
        "site_health_config_invalid_timeouts",
        "site_health_config_public_flag_mismatches",
        "site_health_config_mixed_return_tuple_functions",
        "site_health_config_public_smoke_tools",
        "site_health_config_missing_public_smoke_tools",
        "site_health_config_public_smoke_counters",
        "site_health_config_profile_public_counter_refs",
        "site_health_config_unique_profile_public_counter_refs",
        "site_health_config_missing_public_counter_important_keys",
        "site_health_config_missing_profile_public_counter_snapshots",
        "site_health_config_unknown_profile_public_counter_refs",
        "site_health_config_site_support_files",
        "site_health_config_public_deploy_support_files",
        "site_health_config_public_deploy_missing_support_files",
        "site_health_config_public_deploy_extra_support_files",
        "timed_out",
        "error",
        "elapsed_seconds",
    ]
    emitted_keys: set[str] = set()
    for key in important_keys:
        if key in values:
            lines.append(f"- {key}: `{values[key]}`")
            emitted_keys.add(key)
    for key in sorted(values):
        if key in emitted_keys:
            continue
        if key.endswith("_attempts") or key.endswith("_retry_status"):
            lines.append(f"- {key}: `{values[key]}`")
    return lines


def parse_cloudflare_dry_run(output: str) -> dict[str, str]:
    values = parse_key_values(output)
    for line in output.splitlines():
        for label in ("Commit hash", "Commit message", "Commit dirty", "Static assets", "Remote missing hashes"):
            prefix = f"{label}: "
            if line.startswith(prefix):
                values[label] = line.removeprefix(prefix).strip()
    return values


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a LoveTypes health summary from current checks.")
    parser.add_argument("--output", default=str(DEFAULT_OUTPUT), help="Markdown output path.")
    parser.add_argument(
        "--skip-public",
        action="store_true",
        help="Skip public smoke checks and only summarize local checks plus Cloudflare dry-run.",
    )
    parser.add_argument(
        "--timeout-scale",
        type=float,
        default=1.0,
        help="Multiplier applied to per-check timeouts. Use 0.5 for faster failure or 2 for slow networks.",
    )
    args = parser.parse_args()
    output_path = Path(args.output)
    if not output_path.is_absolute():
        output_path = ROOT / output_path

    head = git_value("rev-parse", "--short", "HEAD")
    full_head = git_value("rev-parse", "HEAD")
    branch = git_value("status", "--short", "--branch").splitlines()[0]
    remote = git_value("ls-remote", "origin", "refs/heads/main").split()
    remote_sha = remote[0] if remote else ""

    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    sections: list[str] = [
        "# LoveTypes Site Health",
        "",
        f"- generated_at_utc: `{generated_at}`",
        f"- commit_short: `{head}`",
        f"- commit_full: `{full_head}`",
        f"- origin_main: `{remote_sha}`",
        f"- branch_status: `{branch}`",
        f"- production: `https://lovetypes.tw/`",
        f"- cloudflare_project: `lovetypes`",
        "",
    ]

    failed = False
    for name, command, timeout, is_public in CHECKS:
        if args.skip_public and is_public:
            print(f"site_health_step={name} status=skipped", flush=True)
            sections.extend([f"## {name}", "", "- status: `skipped`", ""])
            continue
        effective_timeout = max(1, int(timeout * args.timeout_scale))
        print(f"site_health_step={name} status=running timeout={effective_timeout}", flush=True)
        code, output = run(command, timeout=effective_timeout)
        if name == "cloudflare_dry_run":
            values = parse_cloudflare_dry_run(output)
        else:
            values = parse_key_values(output)
        status = check_status(code, values)
        if status != "ok" and name in RETRY_ON_FAILURE:
            print(f"site_health_step={name} status=retrying", flush=True)
            retry_code, retry_output = run(command, timeout=effective_timeout)
            if name == "cloudflare_dry_run":
                retry_values = parse_cloudflare_dry_run(retry_output)
            else:
                retry_values = parse_key_values(retry_output)
            retry_status = check_status(retry_code, retry_values)
            if retry_status == "ok":
                code = retry_code
                values = retry_values
                status = retry_status
            values[f"{name.removesuffix('_smoke')}_retry_status"] = retry_status
            values[f"{name.removesuffix('_smoke')}_attempts"] = "2"
        else:
            values[f"{name.removesuffix('_smoke')}_attempts"] = "1"
        print(f"site_health_step={name} status={status}", flush=True)
        sections.extend(render_section(name, code, values))
        sections.append("")
        if status != "ok":
            failed = True

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(sections).rstrip() + "\n", encoding="utf-8")
    print(f"site_health_output={output_path}")
    print(f"site_health_status={'failed' if failed else 'ok'}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
